#Name: Jan Domingo
#Class Account: CSSC0463
#Class Information: CS570, Spring 2019, Section 1
#Assignment Information: Assignment #1, Hexadecimal Dump File
#Filename: README.txt

#Standard way of compiling shortened by just typing "make" in the command line
xbd:	xbd.c
	gcc xbd.c -o xbd -std=c99

clean:
	rm -f *.0 xbd *~ *.core core