#/****************************************************************************
#Class:		CS 530, Spring 2019
#Project: 	Assignment #2
#Disassembler Program for XE variant of the SIC/XE family
#Names:	Andrew Botros, 819505044, cssc0457
#        Jan Domingo, 820092657, cssc0463
#        Anthony Huynh, 819367270, cssc0458
#Filename: Makefile
#*****************************************************************************/

#Standard way of compiling shortened by just typing "make" in the command line
all:	xed
xed:	main.c	header.h
	gcc main.c -o xed -std=c99
